// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidos.DAL;

namespace RegistroPedidos.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("RegistroPedidos.Entidades.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Monto")
                        .HasColumnType("REAL");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inventario")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 362.95f,
                            Descripcion = "Saco Arroz 15Lb",
                            Inventario = 20
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 36.95f,
                            Descripcion = "Pan Francés",
                            Inventario = 60
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 50f,
                            Descripcion = "Funda Pan Sobao",
                            Inventario = 80
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 124.95f,
                            Descripcion = "Jugo de Naranja",
                            Inventario = 50
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 124.95f,
                            Descripcion = "Jugo de Manzana",
                            Inventario = 50
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 314.95f,
                            Descripcion = "Pierna de Salami",
                            Inventario = 100
                        },
                        new
                        {
                            ProductoId = 7,
                            Costo = 80f,
                            Descripcion = "Leche Evaporada Grande",
                            Inventario = 70
                        },
                        new
                        {
                            ProductoId = 8,
                            Costo = 59.95f,
                            Descripcion = "Leche Evaporada Pequeña",
                            Inventario = 60
                        },
                        new
                        {
                            ProductoId = 9,
                            Costo = 50f,
                            Descripcion = "Funda Pan Sobao",
                            Inventario = 80
                        },
                        new
                        {
                            ProductoId = 10,
                            Costo = 206.95f,
                            Descripcion = "Jamon Caserío",
                            Inventario = 30
                        },
                        new
                        {
                            ProductoId = 11,
                            Costo = 99.95f,
                            Descripcion = "Frasco de Mayonesa",
                            Inventario = 40
                        },
                        new
                        {
                            ProductoId = 12,
                            Costo = 115.95f,
                            Descripcion = "Ketchup",
                            Inventario = 40
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombre = "Induveca"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombre = "Carnation"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombre = "Rica"
                        },
                        new
                        {
                            SuplidorId = 4,
                            Nombre = "Pimco"
                        },
                        new
                        {
                            SuplidorId = 5,
                            Nombre = "Baldom"
                        },
                        new
                        {
                            SuplidorId = 6,
                            Nombre = "Yoma"
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Ordenes", null)
                        .WithMany("DetalleOrden")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
